// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorEcommerce.Server.Data
{
    public partial class Class
    {
        public Guid Classid { get; set; }
        public Guid? Personid { get; set; }
        public string Classname { get; set; }
        public string Note { get; set; }

        //public virtual Person Person { get; set; }
        public virtual ICollection<Person> Person { get; set; }

    }
}