// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorEcommerce.Server.Data
{
    public partial class Finance
    {
        public Guid Financeid { get; set; }
        public DateTime Financedate { get; set; }
        public int? Duedateday { get; set; }
        public Guid? Personid { get; set; }
        public bool Ispaid { get; set; }
        public DateTime? Paymentdate { get; set; }
        public bool Deleted { get; set; }

        public virtual Person Person { get; set; }
    }
}