// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorEcommerce.Server.Data
{
    public partial class Months
    {
        public Months()
        {
            Finance = new HashSet<Finance>();
        }

        public Guid Monthid { get; set; }
        public string Monthname { get; set; }

        public virtual ICollection<Finance> Finance { get; set; }
    }
}