// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorEcommerce.Server.Data
{
    public partial class Person
    {
        public Person()
        {
            Finance = new HashSet<Finance>();
        }

        public Guid Personid { get; set; }
        public Guid? Classid { get; set; }
        public string Fullname { get; set; }
        public string Note { get; set; }
        public string Phone { get; set; }
        public bool Ismature { get; set; }
        public string Parentname { get; set; }
        public bool Deleted { get; set; }

        public virtual Class Class { get; set; }
        public virtual ICollection<Finance> Finance { get; set; }
    }
}