// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorEcommerce.Shared.Models
{
    public partial class FinanceDto
    {
        public Guid Financeid { get; set; }
        public Guid? Monthid { get; set; }
        public Guid? Personid { get; set; }
        public bool? Ispaid { get; set; }
        public string Note { get; set; }
        public DateTime? Lastpaymentdate { get; set; }
        public DateTime? Paymentdate { get; set; }
    }
}