// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorEcommerce.Shared.Models
{
    public partial class MonthsDto
    {

        public Guid Monthid { get; set; }
        public string Monthname { get; set; }

        
    }
}